version = 0.1
[cognito]
[cognito.deploy]
[cognito.deploy.parameters]
stack_name = "egm-cognito"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11t12y9unizis"
s3_prefix = "egm-cognito"
region = "eu-west-1"
profile = "egm"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Project=\"egm\" FirstAdminUserEmail=\"matteo.carbone@iter-idea.com\" FirstAdminUserName=\"Matteo Carbone\""
image_repositories = []

[api-domain]
[api-domain.deploy]
[api-domain.deploy.parameters]
stack_name = "egm-api-domain"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-72wec4gnuoop"
s3_prefix = "egm-api-domain"
region = "eu-south-1"
profile = "egm"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Project=\"egm\" ApiDomainName=\"api-egm.iter-idea.com\" ApiDomainNameForVerification=\"iter-idea.com\""
image_repositories = []

[idea-resources]
[idea-resources.deploy]
[idea-resources.deploy.parameters]
stack_name = "idea-resources"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-72wec4gnuoop"
s3_prefix = "idea-resources"
region = "eu-south-1"
profile = "egm"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "egm-back-end-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-72wec4gnuoop"
s3_prefix = "egm-back-end-prod"
region = "eu-south-1"
profile = "egm"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Project=\"egm\" Environment=\"prod\" CognitoUserPoolRegion=\"eu-west-1\" CognitoUserPoolId=\"eu-west-1_W5470JQ4x\" CognitoUserPoolClientIdFrontEnd=\"b5cb9bombpe5a6i0qt68k1hop\" CognitoUserPoolClientIdBackEnd=\"2054sfkv4h3rrqrusg05gkodm4\""
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "egm-back-end-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-72wec4gnuoop"
s3_prefix = "egm-back-end-dev"
region = "eu-south-1"
profile = "egm"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Project=\"egm\" Environment=\"dev\" CognitoUserPoolRegion=\"eu-west-1\" CognitoUserPoolId=\"eu-west-1_W5470JQ4x\" CognitoUserPoolClientIdFrontEnd=\"b5cb9bombpe5a6i0qt68k1hop\" CognitoUserPoolClientIdBackEnd=\"2054sfkv4h3rrqrusg05gkodm4\""
image_repositories = []

[thumbnailer]
[thumbnailer.deploy]
[thumbnailer.deploy.parameters]
stack_name = "idea-thumbnailer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-72wec4gnuoop"
s3_prefix = "idea-thumbnailer"
region = "eu-south-1"
profile = "egm"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[map]
[map.deploy]
[map.deploy.parameters]
stack_name = "egm-map"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11t12y9unizis"
s3_prefix = "egm-map"
region = "eu-west-1"
profile = "egm"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Project=\"egm\""
image_repositories = []
