AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: IDEA common resources
# it's a separated stack from the back-end's main one so that more env. (e.g. dev, prod) can share the same resources
# it could exist already if there are other projects in this AWS account

Resources:
  ### DDB tables

  IUNIDTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: idea_IUNID
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: project
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: project
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
  AtomicCountersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: idea_atomicCounters
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH

Outputs:
  IUNID:
    Description: IUNID table
    Value: !Ref IUNIDTable
    Export:
      Name: idea:IUNID
  AtomicCounters:
    Description: Atomic counters table
    Value: !Ref AtomicCountersTable
    Export:
      Name: idea:AtomicCounters
