AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Convert an S3 uploaded media into a thumbnail

Resources:
  ThumbnailerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Convert an S3 uploaded media into a thumbnail
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 10
      CodeUri: s3://idea-lambda-functions/fn-thumbnailer.zip
      Handler: index.handler
      FunctionName: idea_thumbnailer
      Tags:
        project: idea
      Environment:
        Variables:
          THUMB_KEY_PREFIX: thumbnails/
          THUMB_HEIGHT: '600'
          THUMB_WIDTH: '600'
      Policies:
        # note well: manual substitution @todo
        - S3CrudPolicy:
            BucketName: egm-dev-media
        - S3CrudPolicy:
            BucketName: egm-prod-media
      Layers:
        - !Ref GhostScriptLayer
        - !Ref ImageMagickLayer
  ThumbnailerFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ThumbnailerFunction}
      RetentionInDays: 14
  GhostScriptLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: idea_ghost_script
      Description: To convert images
      ContentUri: s3://idea-lambda-functions/layer-ghost-script.zip
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x
  GhostScriptLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref GhostScriptLayer
      Principal: !Ref AWS::AccountId
  ImageMagickLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: idea_image_magick
      Description: To convert images
      ContentUri: s3://idea-lambda-functions/layer-image-magick.zip
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: nodejs14.x
  ImageMagickLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref ImageMagickLayer
      Principal: !Ref AWS::AccountId
